### PR TITLE
remember last account

### PR DESCRIPTION
**Pull request by kylepwarren**
remember last account

### CODE REVIEW

**Comment by kylepwarren** [comment]
I stopped tracking the sqlite db, that was a problem! 

It still needs something like migrate scripts so people can upgrade, it doesn't take care of that.

What it takes care of is stopping tracking a file that has personal data. what a blunder.

**Comment by kylepwarren** [comment]
this to upgrade sqlite db w/o migrate like scripts: ALTER TABLE wzusers ADD COLUMN active_account INTEGER NOT NULL DEFAULT (0);

**Comment by kylepwarren** [comment]
I didn't test the auto create column commit, but it looks like it would work - so people can just pull..

Though I was just thinking. the sqlite files, people will have to preserve those one last time. a git pull will either delete it or rename it to the template/original sqlite db.They would have had to preserve it before because it was tracked. So this isn't worse, but also not an improvement until... the pull after this one.

**Comment by prashants** [comment]
Since this patch modifies the data structures and a proper update mechanism needs to be in place for it I will keep this pull request open for now and will include it in next update.

**Pull request closed without merging**
