### PR TITLE
Joomla SSO

### PR DESCRIPTION
**Pull request by keithfjn**
Added support for Joomla SSO.

Important note: A user must be created in Joomla named "admin" to access the admin functionality of Webzash. 
-Licensed under MIT License

EDIT: Added "-Licensed under MIT License"

### CODE REVIEW

**Comment by prashants** [comment]
Good work !

1. Please add MIT license notice
2. Set the default to FALSE and the LoginSystem to empty string

    +Configure::write('Webzash.ThirdPartyLogin', true); /* TRUE / FALSE */
    +Configure::write('Webzash.ThirdPartyLoginSystem', 'JoomlaAuto'); /* e.g. : 'Joomla' or 'JoomlaAuto'*/

3. Reset the value to empty string with a sample value as comment

    define("JOOMLA_LOGOUT_URL", '');
    define("JOOMLA_LOGIN_URL", '');

4. Handle the failed case for $JUser = mysqli_fetch_assoc($R_GetUser);

**Comment by keithfjn** [comment]
The requested changes were made.

Thanks!

**Comment by prashants** [comment]
Please use your email / name in copyright notice rather than mine in JoomlaAuto.php

**Comment by keithfjn** [comment]
Changed.

Sorry for the licensing issues, I don't normally contribute and had assumed it was just a copy/paste for the MIT license.

**Comment by prashants** [comment]
No issues.

**Comment by prashants** [comment]
Changes merged in v2.5-beta branch.

https://github.com/prashants/webzash/tree/v2.5-beta

@keithfjn I have changed the implementation to suit webzash

Closing this pull request.

**Pull request closed without merging**
